yolo_model:

  config_file:
    name: yolov3_custom_train.cfg
  weight_file:
    name: yolov3_custom_train_5000.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - crop
      - easy weed
      - medium weed
      - hard weed
